In [3]:
import pandas as pd

In [4]:
#2020/2021
dataset1 = pd.read_csv(r'Desktop/CSVFILEFOOT/2020-2021.csv')
player1 = dataset1.loc[dataset1['full_name'].str.contains("Santos Gato", case = False) ]
player1

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
538,Rúben Santos Gato Alves Dias,24,863568000,1997/05/14,Premier League,2020/2021,Defender,Manchester City,2845,1420,...,0.6,150,89,711,0,0.13,258,282,5,14

In [5]:
#2019/2020
dataset2 = pd.read_csv(r'Desktop/CSVFILEFOOT/2019-2020.csv')
player2 = dataset2.loc[dataset2['full_name'].str.contains("De Bruyne", case = False) ]
df2 = dataset2.iloc[:,0:20]
df2.head()

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,minutes_played_away,nationality,appearances_overall,appearances_home,appearances_away,goals_overall,goals_home,goals_away,assists_overall,assists_home
0,Aaron Anthony Connolly,21,949017600,2000/01/28,Premier League,2019/2020,Forward,Brighton & Hove Albion,1262,592,670,Republic of Ireland,24,11,13,3,2,1,1,1
1,Aaron Cresswell,32,629683200,1989/12/15,Premier League,2019/2020,Defender,West Ham United,2730,1395,1335,England,31,16,15,3,1,2,0,0
2,Aaron Lennon,34,545529600,1987/04/16,Premier League,2019/2020,Midfielder,Burnley,485,225,260,England,16,9,7,0,0,0,0,0
3,Aaron Mooy,31,653356800,1990/09/15,Premier League,2019/2020,Midfielder,Brighton & Hove Albion,2090,1010,1080,Australia,31,16,15,2,1,1,2,0
4,Aaron Ramsdale,23,895104000,1998/05/14,Premier League,2019/2020,Goalkeeper,AFC Bournemouth,3330,1620,1710,England,37,18,19,0,0,0,1,0

In [6]:
#2018/2019
dataset3 = pd.read_csv(r'Desktop/CSVFILEFOOT/2018-2019.csv')
player3 = dataset3.loc[dataset3['full_name'].str.contains("Virgil", case = False) ]
player3

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
553,Virgil van Dijk,30,678931200,1991/07/08,Premier League,2018/2019,Defender,Liverpool,3385,1675,...,0.51,178,89,3385,1693,0.03,152,201,5,6

In [7]:
#2017/2018
dataset4 = pd.read_csv(r'Desktop/CSVFILEFOOT/2017-2018.csv')
player4 = dataset4.loc[dataset4['full_name'].str.contains("Salah", case = False) ]
player4

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
427,Mohamed Salah,29,708566400,1992/06/15,Premier League,2017/2018,Forward,Liverpool,2922,1556,...,0.89,101,81,2922,292,0.03,1,16,-1,1

In [8]:
#2016/2017
dataset5 = pd.read_csv(r'Desktop/CSVFILEFOOT/2016-2017.csv')
player5 = dataset5.loc[dataset5['full_name'].str.contains("N'Golo", case = False) ]
player5

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
452,N'Golo Kanté,30,670204800,1991/03/29,Premier League,2016/2017,Midfielder,Chelsea,3139,1530,...,0.86,105,90,349,3139,0.26,256,228,-1,11

In [9]:
#2015/2016
dataset6 = pd.read_csv(r'Desktop/CSVFILEFOOT/2015-2016.csv')
player6 = dataset6.loc[dataset6['full_name'].str.contains("Vardy", case = False) ]
player6

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
266,Jamie Vardy,34,537321600,1987/01/11,Premier League,2015/2016,Forward,Leicester City,3140,1576,...,0.86,105,87,449,523,0.2,4,83,-1,1

In [10]:
#2014/2015
dataset7 = pd.read_csv(r'Desktop/CSVFILEFOOT/2014-2015.csv')
player7 = dataset7.loc[dataset7['full_name'].str.contains("Hazard", case = False) ]
player7

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
168,Eden Hazard,31,663206400,1991/01/07,Premier League,2014/2015,Midfielder,Chelsea,3379,1688,...,0.8,113,89,1690,375,0.05,38,37,-1,2

In [11]:
#2013/2014
dataset8 = pd.read_csv(r'Desktop/CSVFILEFOOT/2013-2014.csv')
player8 = dataset8.loc[dataset8['full_name'].str.contains("Suárez", case = False) ]
player8

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
366,Luis Suárez,34,538444800,1987/01/24,Premier League,2013/2014,Forward,Liverpool,2964,1434,...,1.4,64,90,494,247,0.18,2,12,-1,1

In [12]:
#2012/2013
dataset9 = pd.read_csv(r'Desktop/CSVFILEFOOT/2012-2013.csv')
player9 = dataset9.loc[dataset9['full_name'].str.contains("Gareth Bale", case = False) ]
player9

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
193,Gareth Bale,32,616550400,1989/07/16,Premier League,2012/2013,Forward,Tottenham Hotspur,2925,1350,...,1.05,86,89,488,731,0.18,9,124,-1,1

In [13]:
#2011/2012
dataset10 = pd.read_csv(r'Desktop/CSVFILEFOOT/2011-2012.csv')
player10 = dataset10.loc[dataset10['full_name'].str.contains("Vincent Kompany", case = False) ]
player10

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
604,Vincent Kompany,35,513475200,1986/04/10,Premier League,2011/2012,Defender,Manchester City,2774,1424,...,0.65,139,89,396,1387,0.23,170,228,8,9

In [14]:
#2010/2011
dataset11 = pd.read_csv(r'Desktop/CSVFILEFOOT/2010-2011.csv')
player11 = dataset11.loc[dataset11['full_name'].str.contains("Wayne Rooney", case = False) ]
player11

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
614,Wayne Rooney,36,498960000,1985/10/24,Premier League,2010/2011,Forward,Manchester United,2228,1112,...,0.85,106,80,446,223,0.2,30,13,-1,3

In [15]:
#2009/2010
dataset12 = pd.read_csv(r'Desktop/CSVFILEFOOT/2009-2010.csv')
player12 = dataset12.loc[dataset12['full_name'].str.contains("Vidić", case = False) ]
player12

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
444,Nemanja Vidić,40,372470400,1981/10/21,Premier League,2009/2010,Defender,Manchester United,2107,1118,...,0.6,151,88,234,0,0.38,239,308,7,15

In [16]:
fulldata = [player1, player2, player3, player4, player5, player6, player7, player8, player9, player10, player11, player12]
fulldataframe = pd.concat(fulldata)
fulldataframe
fulldataframe.iloc[:,0:20]
Average = fulldataframe['minutes_played_overall'].mean()
Max = fulldataframe['minutes_played_overall'].max()
Min = fulldataframe['minutes_played_overall'].min()
print(Average)
fulldataframe

2884.0

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
538,Rúben Santos Gato Alves Dias,24,863568000,1997/05/14,Premier League,2020/2021,Defender,Manchester City,2845,1420,...,0.60,150,89,711,0,0.13,258,282,5,14
349,Kevin De Bruyne,30,678067200,1991/06/28,Premier League,2019/2020,Midfielder,Manchester City,2800,1403,...,0.68,133,80,933,140,0.10,31,1,-1,4
553,Virgil van Dijk,30,678931200,1991/07/08,Premier League,2018/2019,Defender,Liverpool,3385,1675,...,0.51,178,89,3385,1693,0.03,152,201,5,6
427,Mohamed Salah,29,708566400,1992/06/15,Premier League,2017/2018,Forward,Liverpool,2922,1556,...,0.89,101,81,2922,292,0.03,1,16,-1,1
452,N'Golo Kanté,30,670204800,1991/03/29,Premier League,2016/2017,Midfielder,Chelsea,3139,1530,...,0.86,105,90,349,3139,0.26,256,228,-1,11
266,Jamie Vardy,34,537321600,1987/01/11,Premier League,2015/2016,Forward,Leicester City,3140,1576,...,0.86,105,87,449,523,0.20,4,83,-1,1
168,Eden Hazard,31,663206400,1991/01/07,Premier League,2014/2015,Midfielder,Chelsea,3379,1688,...,0.80,113,89,1690,375,0.05,38,37,-1,2
366,Luis Suárez,34,538444800,1987/01/24,Premier League,2013/2014,Forward,Liverpool,2964,1434,...,1.40,64,90,494,247,0.18,2,12,-1,1
193,Gareth Bale,32,616550400,1989/07/16,Premier League,2012/2013,Forward,Tottenham Hotspur,2925,1350,...,1.05,86,89,488,731,0.18,9,124,-1,1
604,Vincent Kompany,35,513475200,1986/04/10,Premier League,2011/2012,Defender,Manchester City,2774,1424,...,0.65,139,89,396,1387,0.23,170,228,8,9
614,Wayne Rooney,36,498960000,1985/10/24,Premier League,2010/2011,Forward,Manchester United,2228,1112,...,0.85,106,80,446,223,0.20,30,13,-1,3
444,Nemanja Vidić,40,372470400,1981/10/21,Premier League,2009/2010,Defender,Manchester United,2107,1118,...,0.60,151,88,234,0,0.38,239,308,7,15

In [25]:
#Defender DataFrame
defenders = fulldataframe.loc[fulldataframe['position'].str.contains("Defender", case = False) ]
defenders.to_csv(r'Desktop/CSVFILEFOOT/DEFENDER.csv')
#Average cleansheets, conceded goals
DCleanAverage = defenders['clean_sheets_overall'].mean()
DConcededAverage = defenders['conceded_overall'].mean()
print(DCleanAverage)
print(DConcededAverage)
defenders.iloc[:, :26]
defenders

16.5
18.0

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
538,Rúben Santos Gato Alves Dias,24,863568000,1997/05/14,Premier League,2020/2021,Defender,Manchester City,2845,1420,...,0.60,150,89,711,0,0.13,258,282,5,14
553,Virgil van Dijk,30,678931200,1991/07/08,Premier League,2018/2019,Defender,Liverpool,3385,1675,...,0.51,178,89,3385,1693,0.03,152,201,5,6
604,Vincent Kompany,35,513475200,1986/04/10,Premier League,2011/2012,Defender,Manchester City,2774,1424,...,0.65,139,89,396,1387,0.23,170,228,8,9
444,Nemanja Vidić,40,372470400,1981/10/21,Premier League,2009/2010,Defender,Manchester United,2107,1118,...,0.60,151,88,234,0,0.38,239,308,7,15

In [31]:
#Forward DataFrame
forwards = fulldataframe.loc[fulldataframe['position'].str.contains("Forward", case = False) ]
real = forwards.iloc[0:4,0:26]
real['']

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,goals_home,goals_away,assists_overall,assists_home,assists_away,penalty_goals,penalty_misses,clean_sheets_overall,clean_sheets_home,clean_sheets_away
427,Mohamed Salah,29,708566400,1992/06/15,Premier League,2017/2018,Forward,Liverpool,2922,1556,...,19,13,10,8,2,1,1,16,12,4
266,Jamie Vardy,34,537321600,1987/01/11,Premier League,2015/2016,Forward,Leicester City,3140,1576,...,14,10,6,3,3,5,1,14,8,6
366,Luis Suárez,34,538444800,1987/01/24,Premier League,2013/2014,Forward,Liverpool,2964,1434,...,17,14,12,6,6,0,0,7,4,3
193,Gareth Bale,32,616550400,1989/07/16,Premier League,2012/2013,Forward,Tottenham Hotspur,2925,1350,...,8,13,4,2,2,0,0,8,4,4

In [29]:
#Midfielder DataFrame
Midfielders = fulldataframe.loc[fulldataframe['position'].str.contains("Midfielder", case = False) ]
Midfielders.iloc[:,0:26]
MCleanAverage = Midfielders['assists_overall'].mean()
MCleanAverage

10.0